export const APP_NAME = "MDPlanner";
export const APP_VERSION = "2.0.0-alpha";
export const DEFAULT_PORT = 8003;

export const ENTITY_TYPE_LABELS: Record<string, string> = {
  task: "Task",
  note: "Note",
  goal: "Goal",
  milestone: "Milestone",
  idea: "Idea",
  brainstorm: "Brainstorm",
  reflection_template: "Reflection Template",
  reflection: "Reflection",
  retrospective: "Retrospective",
  sticky_note: "Sticky Note",
  mindmap: "Mindmap",
  c4_component: "C4 Component",
  swot: "SWOT",
  risk: "Risk",
  lean_canvas: "Lean Canvas",
  business_model: "Business Model",
  project_value: "Project Value",
  brief: "Brief",
  capacity_plan: "Capacity Plan",
  strategic_builder: "Strategic Builder",
  customer: "Customer",
  rate: "Rate",
  quote: "Quote",
  invoice: "Invoice",
  company: "Company",
  contact: "Contact",
  deal: "Deal",
  interaction: "Interaction",
  portfolio: "Portfolio",
  person: "Person",
  org_member: "Org Member",
  meeting: "Meeting",
  moscow: "MoSCoW",
  eisenhower: "Eisenhower",
  safe_agreement: "SAFe Agreement",
  investor: "Investor",
  kpi_snapshot: "KPI Snapshot",
  onboarding: "Onboarding",
  onboarding_template: "Onboarding Template",
  financial_period: "Financial Period",
  payment: "Payment",
  time_entry: "Time Entry",
  journal: "Journal",
  habit: "Habit",
  dns_domain: "DNS Domain",
  fishbone: "Fishbone",
  marketing_plan: "Marketing Plan",
};
