export const APP_NAME = "MDPlanner";
export const APP_VERSION = "2.0.0-alpha";
export const DEFAULT_PORT = 8003;

export const ENTITY_TYPE_LABELS: Record<string, string> = {
  task: "Task",
  note: "Note",
  goal: "Goal",
  milestone: "Milestone",
  idea: "Idea",
  brainstorm: "Brainstorm",
  reflection_template: "Reflection Template",
  reflection: "Reflection",
  retrospective: "Retrospective",
  sticky_note: "Sticky Note",
  mindmap: "Mindmap",
  c4_component: "C4 Component",
  swot: "SWOT",
  risk: "Risk",
  lean_canvas: "Lean Canvas",
  business_model: "Business Model",
  project_value: "Project Value",
  brief: "Brief",
  capacity_plan: "Capacity Plan",
  strategic_builder: "Strategic Builder",
  customer: "Customer",
  rate: "Rate",
  quote: "Quote",
  invoice: "Invoice",
  company: "Company",
  contact: "Contact",
  deal: "Deal",
  interaction: "Interaction",
  portfolio: "Portfolio",
  person: "Person",
  org_member: "Org Member",
  meeting: "Meeting",
  moscow: "MoSCoW",
  eisenhower: "Eisenhower",
  safe_agreement: "SAFe Agreement",
  investor: "Investor",
  kpi_snapshot: "KPI Snapshot",
  onboarding: "Onboarding",
  onboarding_template: "Onboarding Template",
  financial_period: "Financial Period",
  payment: "Payment",
  time_entry: "Time Entry",
  journal: "Journal",
  habit: "Habit",
  dns_domain: "DNS Domain",
  fishbone: "Fishbone",
  marketing_plan: "Marketing Plan",
};

/** Maps entity FTS type to the URL path prefix for that domain's list view. */
export const ENTITY_TYPE_ROUTES: Record<string, string> = {
  task: "/tasks",
  note: "/notes",
  goal: "/goals",
  milestone: "/milestones",
  idea: "/ideas",
  brainstorm: "/brainstorms",
  reflection_template: "/reflection-templates",
  reflection: "/reflections",
  retrospective: "/retrospectives",
  sticky_note: "/sticky-notes",
  mindmap: "/mindmaps",
  c4_component: "/c4",
  swot: "/swot",
  risk: "/risks",
  lean_canvas: "/lean-canvases",
  business_model: "/business-models",
  project_value: "/project-value",
  brief: "/briefs",
  capacity_plan: "/capacity-plans",
  strategic_builder: "/strategic-builders",
  customer: "/customers",
  rate: "/rates",
  quote: "/quotes",
  invoice: "/invoices",
  company: "/companies",
  contact: "/contacts",
  deal: "/deals",
  interaction: "/interactions",
  portfolio: "/portfolio",
  person: "/people",
  org_member: "/org",
  meeting: "/meetings",
  moscow: "/moscow",
  eisenhower: "/eisenhower",
  safe_agreement: "/safe",
  investor: "/investors",
  kpi_snapshot: "/kpis",
  onboarding: "/onboarding",
  onboarding_template: "/onboarding-templates",
  financial_period: "/finances",
  payment: "/payments",
  time_entry: "/time-entries",
  journal: "/journal",
  habit: "/habits",
  dns_domain: "/dns",
  fishbone: "/fishbones",
  marketing_plan: "/marketing-plans",
};
